version: "3.9"
services:
  localai:
    container_name: llmui-localai
    image: quay.io/go-skynet/local-ai:v0.19.0
    ports:
      - 8080:8080
    volumes:
      - ./models:/models:cached
    environment:
      MODELS_PATH: "/models"
      REBUILD: "false"
      THREADS: 4
      DEBUG: "true"
    command: ["/usr/bin/local-ai"]
